env: local # local|dev|prod

server:
  host: "127.0.0.1"
  port: 8085

logFile:
  use: false
  name: "grpc-gateway.log"

auth_service:
  connect: "localhost:50051"
  negotiation_type: "plaintext" # plaintext | tls
  cert: "" #path to file cert for tls
  max_msg_size: 4
